package com.emines_employee.model.response

data class GetBuyerOrderResponse(
    val address: String,
    val address_type: String,
    val area: String,
    val buyer_id: Int,
    val city: String,
    val country: String,
    val created_at: String,
    val delivery_address_id: Int,
    val id: Int,
    val one_product_gst: String,
    val one_purchased_quantity: Int,
    val one_requested_product: String,
    val one_requested_product_id: Int,
    val one_terms_code: String,
    val one_total_unit_price_excl_gst: String,
    val one_total_unit_price_incl_gst: String,
    val one_unit_of_quantity: String,
    val one_unit_rate: Int,
    val pincode: String,
    val state: String,
    val total_amount_with_gst: String,
    val total_amount_without_gst: String,
    val total_purchased_quantity: Int,
    val two_product_gst: String,
    val two_purchased_quantity: Int,
    val two_requested_product: String,
    val two_requested_product_id: Int,
    val two_terms_code: String,
    val two_total_unit_price_excl_gst: String,
    val two_total_unit_price_incl_gst: String,
    val two_unit_of_quantity: String,
    val two_unit_rate: Int,
    val updated_at: String,
)