package com.emines_employee.model.response

import java.io.Serializable

data class RequestOrderResponse(
    val address: String?=null,
    val address_type: String?=null,
    val area: String?=null,
    val buyer_id: Int,
    val city: String?=null,
    val country: String?=null,
    val created_at: String?=null,
    val delivery_address_id: String?=null,
    val despatch_through: String?=null,
    val destination: String?=null,
    val enter_gate_no: String?=null,
    val four_product_gst: String?=null,
    val four_purchased_quantity: String?=null,
    val four_requested_product: String?=null,
    val four_requested_product_id: String?=null,
    val four_terms_code: String?=null,
    val four_total_unit_price: String?=null,
    val four_total_unit_price_excl_gst: String?=null,
    val four_total_unit_price_incl_gst: String?=null,
    val four_unit_of_quantity: String?=null,
    val four_unit_rate: String?=null,
    val id: Int,
    val indent_no: String?=null,
    val invoice_date: String?=null,
    val invoice_no: String?=null,
    val invoice_status: String?=null,
    val notes: String?=null,
    val one_product_gst: String?=null,
    val one_purchased_quantity: String?=null,
    val one_requested_product: String?=null,
    val one_requested_product_id: String?=null,
    val one_terms_code: String?=null,
    val one_total_unit_price: String?=null,
    val one_total_unit_price_excl_gst: String?=null,
    val one_total_unit_price_incl_gst: String?=null,
    val one_unit_of_quantity: String?=null,
    val one_unit_rate: String?=null,
    val order_no: String?=null,
    val payment_due_date: String?=null,
    val payment_last_term: String?=null,
    val payment_term: String?=null,
    val pincode: String?=null,
    val po_date: String?=null,
    val po_no: String?=null,
    val state: String?=null,
    val status: String?=null,
    val three_product_gst: String?=null,
    val three_purchased_quantity: String?=null,
    val three_requested_product: String?=null,
    val three_requested_product_id: String?=null,
    val three_terms_code: String?=null,
    val three_total_unit_price: String?=null,
    val three_total_unit_price_excl_gst: String?=null,
    val three_total_unit_price_incl_gst: String?=null,
    val three_unit_of_quantity: String?=null,
    val three_unit_rate: String?=null,
    val total_amount: Int,
    val total_amount_with_gst: String?=null,
    val total_amount_without_gst: String?=null,
    val total_order_category: String?=null,
    val total_purchased_quantity: String?=null,
    val total_rate: Int,
    val two_product_gst: String?=null,
    val two_purchased_quantity: String?=null,
    val two_requested_product: String?=null,
    val two_requested_product_id: String?=null,
    val two_terms_code: String?=null,
    val two_total_unit_price: String?=null,
    val two_total_unit_price_excl_gst: String?=null,
    val two_total_unit_price_incl_gst: String?=null,
    val two_unit_of_quantity: String?=null,
    val two_unit_rate: String?=null,
    val updated_at: String?=null,
    val upload_po: String?=null,
    val voucher_no: String?=null,

    val assigned_date: String,
    val denied_date: String,
    val accepte_date: String,
    val pickup_date: String,
    val reached_date: String,
    val delivery_date: String,
    val estimated_delivery_date: String,
    val assigned_to: String,
    val total_orders_againest_po: Int,


    val pickup_weight: String,
    val weight_receipt: String,

    val bill_number: String,
    val eway_bill: String,

    val delivery_weight: String,
    val delivered_weight_receipt: String,

    val grn_number: String,
    val grn_file: String,


):Serializable